sudo: false

notifications:
  email: false

os:
  - osx
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew install yarn;
    fi

install:
  - yarn install
  - yarn vscode:prepublish

script:
  - yarn test --silent
