sudo: false
language: node_js
node_js:
  - 'node'
os:
  - osx
before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
    brew install yarn --without-node;
    fi
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn test --silent
notifications:
  email: false
